name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  google-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Google Test Build
      uses: actions/cache@v2
      id: gtest-cache
      with:
        path: third_party/gtest
        key: gtest-${{ runner.os }}-${GOOGLETEST_VERSION}

    - name: Install required packages
      if: steps.gtest-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget cmake

    - name: Build Google Test
      if: steps.gtest-cache.outputs.cache-hit != 'true'
      run: |
        set -eu

        GOOGLETEST_VERSION="v1.14.0"
        GOOGLEDIR="googletest-1.14.0"

        mkdir -p third_party/
        pushd third_party/
        mkdir gtest
        wget --quiet https://github.com/google/googletest/archive/refs/tags/${GOOGLETEST_VERSION}.tar.gz
        tar -xf ${GOOGLETEST_VERSION}.tar.gz
        rm ${GOOGLETEST_VERSION}.tar.gz
        cd ${GOOGLEDIR}
        mkdir build/
        cd build/
        GPATH=$(pwd)
        cmake .. -DCMAKE_INSTALL_PREFIX=$GPATH/../../gtest
        make
        make install

    - name: Run Google Test
      run: |
        cd test
        make

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test/log/results.log
